# Copyright (c) 2018 Robert Bosch GmbH
# All rights reserved.
#
# This source code is licensed under the BSD-3-Clause license found in the
# LICENSE file in the root directory of this source tree.
#
# @author: Jan Behrens

string name
string[] groups
StringList[] location_names
StringList[] action_types
StringList[] location_description
Domain[] location_domains
Domain[] configuration_domains
Range[] duration_ranges